//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryBrowser.Internationalization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectoryBrowser.Internationalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las miniaturas han sido generadas..
        /// </summary>
        public static string AllThumbsText {
            get {
                return ResourceManager.GetString("AllThumbsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Fichero.
        /// </summary>
        public static string CloseFile {
            get {
                return ResourceManager.GetString("CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string SetupMenu {
            get {
                return ResourceManager.GetString("SetupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quedan {0} miniaturas por generar..
        /// </summary>
        public static string ThumbsLeftText {
            get {
                return ResourceManager.GetString("ThumbsLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado por blopez 2018.
        /// </summary>
        public static string TxtAboutBy {
            get {
                return ResourceManager.GetString("TxtAboutBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string TxtAboutOf {
            get {
                return ResourceManager.GetString("TxtAboutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación.
        /// </summary>
        public static string TxtApp {
            get {
                return ResourceManager.GetString("TxtApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tomos : .
        /// </summary>
        public static string TxtBooks {
            get {
                return ResourceManager.GetString("TxtBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOMOS: .
        /// </summary>
        public static string TxtBooksUpper {
            get {
                return ResourceManager.GetString("TxtBooksUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string TxtCancelTitle {
            get {
                return ResourceManager.GetString("TxtCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string TxtCancelUpper {
            get {
                return ResourceManager.GetString("TxtCancelUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREADO EL: .
        /// </summary>
        public static string TxtCreatedAtUpper {
            get {
                return ResourceManager.GetString("TxtCreatedAtUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Fichero.
        /// </summary>
        public static string TxtCreateFile {
            get {
                return ResourceManager.GetString("TxtCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorar.
        /// </summary>
        public static string TxtExplore {
            get {
                return ResourceManager.GetString("TxtExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero : .
        /// </summary>
        public static string TxtFile {
            get {
                return ResourceManager.GetString("TxtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero creado en {0}.
        /// </summary>
        public static string TxtFileCreatedAt {
            get {
                return ResourceManager.GetString("TxtFileCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero no se encuentra disponible..
        /// </summary>
        public static string TxtFileNotFound {
            get {
                return ResourceManager.GetString("TxtFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro ({0}).
        /// </summary>
        public static string TxtFilter {
            get {
                return ResourceManager.GetString("TxtFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El directorio no se encuentra disponible..
        /// </summary>
        public static string TxtFolderNotFound {
            get {
                return ResourceManager.GetString("TxtFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carpetas : .
        /// </summary>
        public static string TxtFolders {
            get {
                return ResourceManager.GetString("TxtFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde fichero.
        /// </summary>
        public static string TxtFromFile {
            get {
                return ResourceManager.GetString("TxtFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde sistema.
        /// </summary>
        public static string TxtFromSystem {
            get {
                return ResourceManager.GetString("TxtFromSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pantalla completa.
        /// </summary>
        public static string TxtFullScreen {
            get {
                return ResourceManager.GetString("TxtFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERANDO LIBRERIA....
        /// </summary>
        public static string TxtGenaratingLibraryTitle {
            get {
                return ResourceManager.GetString("TxtGenaratingLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMACIÓN.
        /// </summary>
        public static string TxtInfoTItle {
            get {
                return ResourceManager.GetString("TxtInfoTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string TxtLanguageEN {
            get {
                return ResourceManager.GetString("TxtLanguageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string TxtLanguageES {
            get {
                return ResourceManager.GetString("TxtLanguageES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDIOMA.
        /// </summary>
        public static string TxtLanguageTitle {
            get {
                return ResourceManager.GetString("TxtLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  ÚLTIMOS COMICS ACTUALIZADOS.
        /// </summary>
        public static string TxtLastComicsUpdatedUpper {
            get {
                return ResourceManager.GetString("TxtLastComicsUpdatedUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ULTIMA ACTUALIZACIÓN: .
        /// </summary>
        public static string TxtLastUpdatedUpper {
            get {
                return ResourceManager.GetString("TxtLastUpdatedUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CARGANDO....
        /// </summary>
        public static string TxtLoadingUpper {
            get {
                return ResourceManager.GetString("TxtLoadingUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MIS COMICS.
        /// </summary>
        public static string TxtMyComicsTitle {
            get {
                return ResourceManager.GetString("TxtMyComicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEPTAR.
        /// </summary>
        public static string TxtOkUpper {
            get {
                return ResourceManager.GetString("TxtOkUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Fichero.
        /// </summary>
        public static string TxtOpenFile {
            get {
                return ResourceManager.GetString("TxtOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando {0} de {1} carpetas, {2} de {3} ficheros..
        /// </summary>
        public static string TxtProcessing {
            get {
                return ResourceManager.GetString("TxtProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROCESANDO....
        /// </summary>
        public static string TxtProcessTitle {
            get {
                return ResourceManager.GetString("TxtProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LECTOR UTILIZADO.
        /// </summary>
        public static string TxtReaderUseTitle {
            get {
                return ResourceManager.GetString("TxtReaderUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar página.
        /// </summary>
        public static string TxtSavePage {
            get {
                return ResourceManager.GetString("TxtSavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        public static string TxtSaveTitle {
            get {
                return ResourceManager.GetString("TxtSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string TxtSearch {
            get {
                return ResourceManager.GetString("TxtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIGURACIÓN.
        /// </summary>
        public static string TxtSetupTitle {
            get {
                return ResourceManager.GetString("TxtSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño : .
        /// </summary>
        public static string TxtSize {
            get {
                return ResourceManager.GetString("TxtSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ORIGEN MINIATURAS.
        /// </summary>
        public static string TxtSourceThumbsTitle {
            get {
                return ResourceManager.GetString("TxtSourceThumbsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string TxtSystem {
            get {
                return ResourceManager.GetString("TxtSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TITULO: .
        /// </summary>
        public static string TxtTitleUpper {
            get {
                return ResourceManager.GetString("TxtTitleUpper", resourceCulture);
            }
        }
    }
}
